name: Check Terraform Format

on:
  workflow_call:

jobs:
  check-terraform-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          export BRANCH_NAME=origin/${{ github.event.repository.default_branch }}
          export PRECOMMIT=false
          run: ./scripts/githooks/terraform-pre-commit.sh
